worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      SESSION_NAME: $SESSION_NAME
      BOT_TOKEN: $BOT_TOKEN
      BOT_NAME: $BOT_NAME
@@ -12,8 +14,7 @@ services:
      ASSUSERNAME: $ASSUSERNAME
      BOT_ID: $BOT_ID
      MONGO_DB_URI: $MONGO_DB_URI
      API_ID: $API_ID
      API_HASH: $API_HASH

      OWNER_ID: $OWNER_ID
      UPDATE: $UPDATE
      SUPPORT: $SUPPORT